<?php
/**
 * Created by PhpStorm.
 * User: LiuJie
 * Date: 2018/2/8
 * Time: 上午11:28
 */
namespace app\index\controller;
use think\Controller;
use think\Session;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        define('USER_ID', Session::get('user_id'));
    }

    //判断用户是否登录   在index/index下面
    protected function isLogin()
    {
        if (empty(USER_ID)){
            $this->error('用户未登录，无权访问.正返回登录界面...', '/index/user/login');
        }
    }

    protected function alreadyLogin()
    {
        if (!empty(USER_ID)){
            $this->error('用户已经登录，请勿重新登录...', '/index/index', '',2);
        }
    }
}